// <auto-generated> from BorkelRNVG 3.0.4 (0b238cb) masks. Do not edit. </auto-generated>
namespace Coti.Shared
{
  public static partial class CotiLayouts
  {
    public static readonly CotiLayout Quad = new CotiLayout( "quad", CotiTubes.Tube2, new[]
    {
      new CotiLayoutTube( CotiTubes.Tube0, -0.74984f, -0.00084f, 0.28506f ),
      new CotiLayoutTube( CotiTubes.Tube1, -0.06604f, -0.00084f, 0.28506f ),
      new CotiLayoutTube( CotiTubes.Tube2, +0.06604f, -0.00084f, 0.28506f ),
      new CotiLayoutTube( CotiTubes.Tube3, +0.74984f, -0.00084f, 0.28506f ),
    } );
    public static readonly CotiLayout Dual = new CotiLayout( "dual", CotiTubes.Tube2, new[]
    {
      new CotiLayoutTube( CotiTubes.Tube1, -0.06276f, -0.00086f, 0.27362f ),
      new CotiLayoutTube( CotiTubes.Tube2, +0.06276f, -0.00086f, 0.27362f ),
    } );
    public static readonly CotiLayout Mono = new CotiLayout( "mono", CotiTubes.Center, new[]
    {
      new CotiLayoutTube( CotiTubes.Center, +0.00099f, -0.00079f, 0.27359f ),
    } );
    public static readonly CotiLayout Pvs5a = new CotiLayout( "pvs5a", CotiTubes.Tube2, new[]
    {
      new CotiLayoutTube( CotiTubes.Tube1, -0.01509f, +0.00756f, 0.24311f ),
      new CotiLayoutTube( CotiTubes.Tube2, +0.00380f, +0.00563f, 0.24311f ),
    } );
  }
}
